"""DTX model: GM-drum -> lane mapping, quantized note grid, DTX emit + zip packaging."""
import os, math, zipfile
from fractions import Fraction
from functools import reduce

GRID = 64  # slots per whole-note

# GM MIDI drum -> (DTX channel, WAV label)
MAP = {
    36: ("13", "bd"), 35: ("13", "bd"),
    38: ("12", "sd"), 40: ("12", "sd"), 37: ("12", "sd"),
    42: ("11", "hh"), 44: ("1B", "lp"), 46: ("18", "ho"),
    48: ("14", "ht"), 50: ("14", "ht"),
    45: ("15", "lt"), 47: ("15", "lt"),
    41: ("17", "ft"), 43: ("17", "ft"),
    49: ("16", "cy"), 57: ("1A", "cy"), 55: ("16", "cy"), 52: ("1A", "cy"),
    51: ("19", "rd"), 59: ("19", "rd"), 53: ("19", "rb"),
}

# WAV slot assignments (2-char labels in DTX). 01 reserved for BGM.
WAV_SLOTS = [
    ("02", "bd"), ("03", "sd"), ("04", "hh"), ("05", "ho"), ("06", "ht"),
    ("07", "lt"), ("08", "ft"), ("09", "cy"), ("0A", "rd"), ("0B", "rb"), ("0C", "lp"),
]
LABEL2SLOT = {lab: slot for slot, lab in WAV_SLOTS}
LANE_ORDER = ["13", "12", "11", "18", "1B", "14", "15", "17", "16", "1A", "19"]

# DTXMania / GITADORA difficulty tiers, keyed by the 0.00-9.99 auto-difficulty score.
# Each: (key, .dtx filename, set.def label, set.def Ln slot, low, high)  -- range is [low, high)
DIFF_TIERS = [
    ("basic",    "bsc.dtx",  "BASIC",    1, 0.00, 2.50),
    ("advanced", "adv.dtx",  "ADVANCED", 2, 2.50, 5.00),
    ("extreme",  "ext.dtx",  "EXTREME",  3, 5.00, 8.00),
    ("master",   "mstr.dtx", "MASTER",   4, 8.00, 10.01),
]
_TIER_BY_KEY = {t[0]: t for t in DIFF_TIERS}


def tier_from_score(score):
    """Map a 0.00-9.99 difficulty score to a tier key (basic/advanced/extreme/master)."""
    s = max(0.0, min(9.99, float(score)))
    for key, _fn, _lbl, _slot, lo, hi in DIFF_TIERS:
        if lo <= s < hi:
            return key
    return "master"


def tier_info(key):
    """Return (dtx_filename, set.def label, set.def slot) for a tier key."""
    t = _TIER_BY_KEY.get(str(key).lower(), _TIER_BY_KEY["extreme"])
    return t[1], t[2], t[3]

def _lcm(a, b): return a * b // math.gcd(a, b)


def events_from_tab(measures):
    """Songsterr drum measures -> (events, barlens) with forced true meter +
    grid quantization so phantom overflow notes merge and tempo stays locked."""
    events, barlens = [], []
    cur_sig = (4, 4)
    for m in measures:
        s = m.get("signature")
        if s:
            cur_sig = (int(s[0]), int(s[1]))
        nominal = Fraction(cur_sig[0], cur_sig[1])
        bar_slots = max(1, round(float(nominal) * GRID))
        chan = {}
        for v in m.get("voices", []):
            cum = Fraction(0)
            for b in v.get("beats", []):
                d = b.get("duration"); dur = Fraction(d[0], d[1]) if d else Fraction(0)
                if not b.get("rest"):
                    slot = int(round(float(cum) * GRID))
                    if slot >= bar_slots:
                        slot = bar_slots - 1
                    pos = Fraction(slot, bar_slots)
                    for n in b.get("notes", []):
                        if n.get("rest"):
                            continue
                        fr = n.get("fret")
                        if fr in MAP:
                            ch, lab = MAP[fr]
                            chan.setdefault(ch, {}).setdefault(pos, LABEL2SLOT[lab])
                cum += dur
        events.append(chan)
        barlens.append(nominal)
    return events, barlens


def _chan_line(mi, ch, slotmap):
    positions = list(slotmap.keys())
    denoms = [p.denominator for p in positions if p != 0] or [1]
    N = max(reduce(_lcm, denoms, 1), 1)
    cells = ["00"] * N
    for p, lab in slotmap.items():
        idx = int(p * N)
        if 0 <= idx < N:
            cells[idx] = lab
    return f"#{mi:03d}{ch}: " + "".join(cells)


def emit_dtx(events, barlens, meta):
    """Render the .dtx text. meta: dict(title, artist, bpm, dlevel, comment, bgm)."""
    L = ["; DTXManiaNX chart -- generated by DTX Forge"]
    L += [f"#TITLE: {meta['title']}", f"#ARTIST: {meta['artist']}",
          f"#COMMENT: {meta.get('comment','')}", f"#DLEVEL: {meta.get('dlevel',50)}",
          f"#BPM: {meta['bpm']}", ""]
    L.append(f"#WAV01: {meta['bgm']}")
    for slot, lab in WAV_SLOTS:
        L.append(f"#WAV{slot}: {lab}.wav")
    L.append("")
    for slot, lab in WAV_SLOTS:
        L.append(f"#VOLUME{slot}: {meta.get('sample_volume',85)}")
    L += ["", "; ---- body ----", "#00001: 01"]
    for i, bl in enumerate(barlens):
        if bl != Fraction(1):
            L.append(f"#{i:03d}02: {float(bl):g}")
    L.append("")
    for i, chan in enumerate(events):
        wrote = False
        for ch in LANE_ORDER:
            if chan.get(ch):
                L.append(_chan_line(i, ch, chan[ch])); wrote = True
        if wrote:
            L.append("")
    return "\n".join(L) + "\n"


def count_chips(events):
    return sum(len(sm) for ch in events for sm in ch.values())


def package(out_dir, song_name, dtx_text, bgm_src, kit_dir, kit_files,
            dtx_name="chart.dtx", set_label="Drums", set_slot=1):
    """Write folder <out_dir>/<song_name>/ with dtx + bgm + kit wavs, then zip it.
    dtx_name / set_label / set_slot follow the DTXMania difficulty-tier convention
    (e.g. ext.dtx in set.def slot L3 labelled EXTREME)."""
    import shutil
    folder = os.path.join(out_dir, song_name)
    os.makedirs(folder, exist_ok=True)
    for f in os.listdir(folder):
        try: os.remove(os.path.join(folder, f))
        except OSError: pass
    with open(os.path.join(folder, dtx_name), "w", encoding="shift_jis", errors="replace") as fh:
        fh.write(dtx_text)
    # set.def -- place the chart in its difficulty slot with the tier label
    with open(os.path.join(folder, "set.def"), "w", encoding="shift_jis", errors="replace") as fh:
        fh.write(f"#TITLE {song_name}\n#L{set_slot}LABEL {set_label}\n#L{set_slot}FILE {dtx_name}\n")
    # bgm
    shutil.copy2(bgm_src, os.path.join(folder, os.path.basename(bgm_src)))
    # kit
    for lab, fn in kit_files.items():
        shutil.copy2(os.path.join(kit_dir, fn), os.path.join(folder, fn))
    # zip
    zpath = os.path.join(out_dir, song_name + ".zip")
    if os.path.exists(zpath):
        try: os.remove(zpath)
        except OSError: pass
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(os.listdir(folder)):
            z.write(os.path.join(folder, f), os.path.join(song_name, f))
    return folder, zpath
